details = [
  {
    album_title: "Stoned & Dethroned",
    artist: "The Jesus and Mary Chain",
    album_time: "August 1994",
    time: "April 2012",
    location: "Fenghuang, China",
    text: "This is a much calmer album from JAMC. I was traveling to the rural and ancient part of China, just before graduation from undergrad. Had fun with friend, but I was sad that my exam conflicted with JAMC\'s concert in Beijing. Listening to it on the old green train in the middle of China, the music flew with the time and the wild landscape.",
  },
  {
    album_title: "Souvlaki",
    artist: "Slowdive",
    album_time: "May 1993",
    time: "May 2012",
    location: "Shanghai, China",
    text: "I was quite anxious about my bachelor thesis at that time, and Slowdive helped to soothe me a lot. I was humming 40 Days going back to the dorm from library, and continued playing it while coding at night. I love the dreamy atmosphere and the shoegaze guitar sound.",
  },
  {
    album_title: "Unknown Pleasures",
    artist: "Joy Division",
    album_time: "June 1979",
    time: "March 2011",
    location: "Shanghai, China",
    text: "I was walking around the main campus of Fudan, and listening to this really dark album on loops. Some friends were concerned about my state, worrying that I had suicidal thoughts. Actually I wasn't that depressed, I was just very unsure about life, where I was heading for, and the constant feeling that I was a failure.",
  },
  {
    album_title: "The Stone Roses",
    artist: "The Stone Roses",
    album_time: "April 1989",
    time: "November 2010",
    location: "Shanghai, China",
    text: "Shanghai's winter was painfully cold. The classes were dull, and coursework took lots of time. Occasionally I was walking alone on the quiet roads, or buying lunch in local convenience stores, this album always lighted up my mood. And sure, I wanna be adored.",
  },
  {
    album_title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    album_time: "March 1973",
    time: "June 2009",
    location: "Shanghai, China",
    text: "That was the end of my freshman year, my last year on the main campus of Fudan, a sunny and lovely place. This album got me wandering around and around the campus, thinking about time, money, wondering how this wonderful, creative music could possibly be composed at that time. I saw this pair of converse in the center of Shanghai, and wanted them so much.",
  },
  {
    album_title: "Honey's Dead",
    artist: "The Jesus and Mary Chain",
    album_time: "March 1992",
    time: "November 2011",
    location: "Shanghai, China",
    text: "I was interning in the financial area of Shanghai, and applying to grad schools in the US. It was a very stressful period of time. Every day I would listen to JAMC on my way back from work, walking through the cold wind alone to the subway station. It helped to relieve, and re-filled me with energy and passion.",
  },
  {
    album_title: "Going Blank Again",
    artist: "Ride",
    album_time: "March 1992",
    time: "May 2013",
    location: "Stanford, USA",
    text: "I was trying to choose one song to present in my rock history class so I was reviewing Ride at the time. Many times I went to Crown Law School alone on weekends, I was listening to this one. It's loud but it's weirdly soothing. At Stanford, I often got overwhelmed by lots of thoughts going on at the same time, and Ride helped me to Leave Them All Behind."
  },
  {
    album_title: "What Did You Expect from The Vaccines?",
    artist: "The Vaccines",
    album_time: "March 2011",
    time: 'August 2013',
    location: 'Chicago, USA',
    text: "The Vaccines is not a complicated, artsy band I usually like. It\'s simple and energetic. The composition is nothing complicated, but it could be addictive. They have helped me pass the long commute time on caltrain to San Francisco every day during that summer. Saw them at lollapalooza 2013 with friends on the east coast.",
  },
  {
    album_title: "Nowhere",
    artist: "Ride",
    album_time: "October 1990",
    time: "December 2012",
    location: "Shanghai, China",
    text: "At the time I was interning and applying for grad schools in the US. Though stressful, there were many new sparks in my life, I was meeting a lot of people in design and tech startups in Shanghai, and was greatly inspired. Back to dorm, nobody's interested in my new life. I put on my headphones and enjoyed Ride.",
  }
];