details = [
  {
    album_title: "Stoned & Dethroned",
    artist: "The Jesus and Mary Chain",
    album_time: "Aug. 1994",
    time: "Apr. 2012",
    year: 2012,
    month: 4,
    location: "Fenghuang, China",
    text: "This is a much calmer album from JAMC. I was traveling to the rural and ancient part of China, just before graduation from undergrad. Had fun with friend, but I was sad that my exam conflicted with JAMC\'s concert in Beijing. Listening to it on the old green train in the middle of China, the music flew with the time and the wild landscape.",
  },
  {
    album_title: "Souvlaki",
    artist: "Slowdive",
    album_time: "May 1993",
    time: "May 2012",
    year: 2012,
    month: 5,
    location: "Shanghai, China",
    text: "I was quite anxious about my bachelor thesis at that time, and Slowdive helped to soothe me a lot. I was humming 40 Days going back to the dorm from library, and continued playing it while coding at night. I love the dreamy atmosphere and the shoegaze guitar sound.",
  },
  {
    album_title: "Unknown Pleasures",
    artist: "Joy Division",
    album_time: "Jun. 1979",
    time: "Mar. 2011",
    year: 2011,
    month: 3,
    location: "Shanghai, China",
    text: "I was walking around the main campus of Fudan, and listening to this really dark album on loops. Some friends were concerned about my state, worrying that I had suicidal thoughts. Actually I wasn't that depressed, I was just very unsure about life, where I was heading for, and the constant feeling that I was a failure.",
  },
  {
    album_title: "The Stone Roses",
    artist: "The Stone Roses",
    album_time: "Apr. 1989",
    time: "Nov. 2010",
    year: 2010,
    month: 11,
    location: "Shanghai, China",
    text: "Shanghai's winter was painfully cold. The classes were dull, and coursework took lots of time. Occasionally I was walking alone on the quiet roads, or buying lunch in local convenience stores, this album always lighted up my mood. And sure, I wanna be adored.",
  },
  {
    album_title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    album_time: "Mar. 1973",
    time: "Jun. 2009",
    year: 2009,
    month: 6,
    location: "Shanghai, China",
    text: "That was the end of my freshman year, my last year on the main campus of Fudan, a sunny and lovely place. This album got me wandering around and around the campus, thinking about time, money, wondering how this wonderful, creative music could possibly be composed at that time. I saw this pair of converse in the center of Shanghai, and wanted them so much.",
  },
  {
    album_title: "Honey's Dead",
    artist: "The Jesus and Mary Chain",
    album_time: "Mar. 1992",
    time: "Nov. 2011",
    year: 2011,
    month: 11,
    location: "Shanghai, China",
    text: "I was interning in the financial area of Shanghai, and applying to grad schools in the US. It was a very stressful period of time. Every day I would listen to JAMC on my way back from work, walking through the cold wind alone to the subway station. It helped to relieve, and re-filled me with energy and passion.",
  },
  {
    album_title: "Going Blank Again",
    artist: "Ride",
    album_time: "Mar. 1992",
    time: "May 2013",
    year: 2013,
    month: 5,
    location: "Stanford, USA",
    text: "I was trying to choose one song to present in my rock history class so I was reviewing Ride at the time. Many times I went to Crown Law School alone on weekends, I was listening to this one. It's loud but it's weirdly soothing. At Stanford, I often got overwhelmed by lots of thoughts going on at the same time, and Ride helped me to Leave Them All Behind."
  },
  {
    album_title: "What Did You Expect from The Vaccines?",
    artist: "The Vaccines",
    album_time: "Mar. 2011",
    time: 'Aug. 2013',
    year: 2013,
    month: 8,
    location: 'Chicago, USA',
    text: "The Vaccines is not a complicated, artsy band I usually like. It\'s simple and energetic. The composition is nothing complicated, but it could be addictive. They have helped me pass the long commute time on caltrain to San Francisco every day during that summer. Saw them at lollapalooza 2013 with friends on the east coast.",
  },
  {
    album_title: "Nowhere",
    artist: "Ride",
    album_time: "Oct. 1990",
    time: "Dec. 2012",
    year: 2012,
    month: 12,
    location: "Shanghai, China",
    text: "At the time I was interning and applying for grad schools in the US. Though stressful, there were many new sparks in my life, I was meeting a lot of people in design and tech startups in Shanghai, and was greatly inspired. Back to dorm, nobody's interested in my new life. I put on my headphones and enjoyed Ride.",
  },
  {
    album_title: "Quarantine the Past: The Best of Pavement",
    artist: "Pavement",
    album_time: "Mar. 2010",
    time: "Nov. 2013",
    year: 2013,
    month: 11,
    location: "Stanford, USA",
    text: "Those stressful times coding at meyer, Pavement was my working music. It's easy on the ear but its twists, and low-fi flavor made it interesting, and entertaining while coding.",
  },
  {
    album_title: "Green Mind",
    artist: "Dinosaur Jr",
    album_time: "Feb. 1991",
    time: "Aug. 2012",
    year: 2012,
    month: 8,
    location: "Yichang, China",
    text: "",
  },
  {
    album_title: "Darklands",
    artist: "The Jesus and Mary Chain",
    album_time: "Aug. 1987",
    time: "Jun. 2011",
    year: 2011,
    month: 6,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "B.R.M.C.",
    artist: "Black Rebel Motorcycle Club",
    album_time: "Apr. 2001",
    time: "Jun. 2012",
    year: 2012,
    month: 6,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Automatic",
    artist: "The Jesus and Mary Chain",
    album_time: "Oct. 1989",
    time: "Jul. 2011",
    year: 2011,
    month: 7,
    location: "Dublin, Ireland",
    text: "",
  },
  {
    album_title: "Psychocandy",
    artist: "The Jesus and Mary Chain",
    album_time: "Nov. 1985",
    time: "May 2012",
    year: 2012,
    month: 5,
    location: "Beijing, China",
    text: "",
  },
  {
    album_title: "Kid A",
    artist: "Radiohead",
    album_time: "Oct. 2000",
    time: "Oct. 2010",
    year: 2010,
    month: 10,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Attack of the Grey Lantern",
    artist: "Mansun",
    album_title: "Feb. 1997",
    time: "Apr. 2012",
    year: 2012,
    month: 4,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Doolittle",
    artist: "Pixies",
    album_time: "Apr. 1989",
    time: "Feb. 2011",
    year: 2011,
    month: 2,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "The Best of New Order",
    artist: "New Order",
    album_time: "Nov. 1994",
    time: "Dec. 2010",
    year: 2010,
    month: 12,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Yuck",
    artist: "Yuck",
    album_time: "Feb. 2011",
    time: "Jun. 2012",
    year: 2012,
    month: 6,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Different Class",
    artist: "Pulp",
    album_time: "Oct. 1995",
    time: "Nov. 2012",
    year: 2012,
    month: 11,
    location: "Stanford, USA",
    text: "",
  },
  {
    album_title: "Men's Needs, Women's Needs, Whatever",
    artist: "The Cribs",
    album_time: "May 2007",
    time: "Dec. 2011",
    year: 2011,
    month: 12,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "The Pleasure Principle",
    artist: "Gary Numan",
    album_time: "Sep. 1979",
    time: "Jul. 2012",
    year: 2012,
    month: 7,
    location: "Yichang, China",
    text: "",
  },
  {
    album_title: "Disintegration",
    artist: "The Cure",
    album_time: "May 1989",
    time: "Jan. 2011",
    year: 2011,
    month: 1,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "London Calling",
    artist: "The Clash",
    album_time: "Dec. 1979",
    time: "May 2011",
    year: 2011,
    month: 5,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Turn on the Bright Lights",
    artist: "Interpol",
    album_time: "Aug. 2002",
    time: "Jun. 2012",
    year: 2012,
    month: 6,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Closer",
    artist: "Joy Division",
    album_time: "Jul. 1980",
    time: "Dec. 2010",
    year: 2010,
    month: 12,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Visage",
    artist: "Visage",
    album_time: "Nov. 1980",
    time: "Nov. 2013",
    year: 2013,
    month: 11,
    location: "Stanford, USA",
    text: "",
  },
  {
    album_title: "Time for Heroes – The Best of The Libertines",
    artist: "The Libertines",
    album_time: "Oct. 2007",
    time: "Nov. 2008",
    year: 2008,
    month: 11,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "Hissing Fauna, Are You the Destroyer?",
    artist: "Of Montreal",
    album_time: "Jan. 2007",
    time: "Jul. 2012",
    year: 2012,
    month: 7,
    location: "Yichang, China",
    text: "",
  },
  {
    album_title: "She Hangs Brightly",
    artist: "Mazzy Star",
    album_time: "May 1990",
    time: "Jan. 2012",
    year: 2012,
    month: 1,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "The Queen Is Dead",
    artist: "The Smiths",
    album_time: "Jun. 1986",
    time: "Mar. 2009",
    year: 2009,
    month: 3,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "You Could Have It So Much Better",
    artist: "Franz Ferdinand",
    album_time: "Oct. 2005",
    time: "Nov. 2009",
    year: 2009,
    month: 11,
    location: "Shanghai, China",
    text: "",
  },
  {
    album_title: "23",
    artist: "Blonde Redhead",
    album_time: "Apr. 2007",
    time: "Jul. 2012",
    year: 2012,
    month: 7,
    location: "Yichang, China",
    text: "",
  },
  {
    album_title: "On Fire",
    artist: "Galaxie 500",
    album_time: "Jan. 1989",
    time: "Dec. 2012",
    year: 2012,
    month: 12,
    location: "Stanford, USA",
    text: "",
  },
  {
    album_title: "Four-Calendar Café",
    artist: "Cocteau Twins",
    album_time: "Nov. 1993",
    time: "Oct. 2012",
    year: 2012,
    month: 10,
    location: "Stanford, USA",
    text: "",
  },
  {
    album_title: "Dummy",
    artist: "Portishead",
    album_time: "Aug. 1994",
    time: "Jan. 2010",
    year: 2010,
    month: 1,
    location: "Yichang, China",
    text: "",
  }
];